
-- Tabela de Configurações do Catálogo
create table if not exists public.catalog_settings (
    id bigint generated by default as identity primary key,
    min_year int default 1900,
    max_year int default 2100,
    selected_genres jsonb default '[]'::jsonb,
    content_type text default 'mixed', -- 'movies', 'series', 'mixed'
    updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Inserir configuração padrão se não existir
insert into public.catalog_settings (id, min_year, max_year, selected_genres, content_type)
select 1, 1900, 2100, '[]'::jsonb, 'mixed'
where not exists (select 1 from public.catalog_settings where id = 1);

-- Índices de Performance (se já não existirem, o IF NOT EXISTS ou verificação manual é ideal, mas aqui é o script bruto)
-- CREATE INDEX IF NOT EXISTS idx_movies_release_date ON movies(release_date);
-- CREATE INDEX IF NOT EXISTS idx_series_first_air_date ON series(first_air_date);
-- CREATE UNIQUE INDEX IF NOT EXISTS idx_movies_tmdb_unique ON movies(tmdb_id);
-- CREATE UNIQUE INDEX IF NOT EXISTS idx_series_tmdb_unique ON series(tmdb_id);
